### ISSUE TITLE
Conjugations missing type in cli

### ISSUE THREAD

**Issue by Shadowlauch** [tshatrov/ichiran#13]
First of all: Thank you very much for this amazing project and the work you put into the blog post to make the common lisp folk available to people who have never done anything with it. This project is truly a game changer!

I set up the cli yesterday and I had it running in no time. Today I started making a simple frontend for my project and I noticed that the conj.prop.type array is always empty. To make sure I tried the same example directly in the lisp command line and it worked fine.

As a simple example I used できなかった:
```json
[[[[["dekinakatta",{"reading":"\u3067\u304D\u306A\u304B\u3063\u305F","text":"\u3067\u304D\u306A\u304B\u3063\u305F","kana":"\u3067\u304D\u306A\u304B\u3063\u305F","score":525,"seq":10027599,"conj":[{"prop":[{"pos":"v1","type":[],"neg":true}],"reading":"\u51FA\u6765\u308B \u3010\u3067\u304D\u308B\u3011","gloss":[{"pos":"[v1,vi]","gloss":"to be able (in a position) to do; to be up to the task"},{"pos":"[v1,vi]","gloss":"to be ready; to be completed"},{"pos":"[v1,vi]","gloss":"to be made; to be built"},{"pos":"[v1,vi]","gloss":"to be good at; to be permitted (to do)"},{"pos":"[v1,vi]","gloss":"to become intimate; to take up (with somebody)"},{"pos":"[v1,vi]","gloss":"to grow; to be raised"},{"pos":"[vi,v1]","gloss":"to become pregnant"}],"readok":true}]},[]]],525]]]
```

**Comment by tshatrov** [comment]
Well, it does work for me...
```
[[[[["dekinakatta",{"reading":"\u3067\u304D\u306A\u304B\u3063\u305F","text":"\u3067\u304D\u306A\u304B\u3063\u305F","kana":"\u3067\u304D\u306A\u304B\u3063\u305F","score":525,"seq":10027599,"conj":[{"prop":[{"pos":"v1","type":"Past (~ta)","neg":true}],"reading":"\u51FA\u6765\u308B \u3010\u3067\u304D\u308B\u3011","gloss":[{"pos":"[v1,vi]","gloss":"to be able (in a position) to do; to be up to the task"},{"pos":"[v1,vi]","gloss":"to be ready; to be completed"},{"pos":"[v1,vi]","gloss":"to be made; to be built"},{"pos":"[v1,vi]","gloss":"to be good at; to be permitted (to do)"},{"pos":"[v1,vi]","gloss":"to become intimate; to take up (with somebody)"},{"pos":"[v1,vi]","gloss":"to grow; to be raised"},{"pos":"[vi,v1]","gloss":"to become pregnant"}],"readok":true}]},[]]],525]]]
```

I think the problem might be related to the fact that the type name is taken from jmdict data file `conj.csv`. If the executable somehow doesn't have access to this file (even though your shell apparently does) then "type" becomes `nil` on Lisp end, which is then converted to empty list in json.

Consider running the following command

```
ichiran-cli -e "ichiran/dict::*jmdict-data*"
```

Does it return a directory that has `conj.csv` in it?

I guess the data from these files really should really be loaded in during the build process so that the executable doesn't require them anymore, so I'll probably fix this in the next release.

**Comment by Shadowlauch** [comment]
Hey thanks for the answer. I found the problem I had. When initially building the cli I had a wrong path in the settings.lisp file and I did not notice that the script was not overwriting the cli after the first build. I just had to delete the exe and build again.
