### ISSUE TITLE
Slow parsing speed

### ISSUE THREAD

**Issue by sethzh** [tshatrov/ichiran#17]
This may be impossible to do anything about, but is there a way to increase the speed of the parser?

This is by far the most accurate Japanese parser I've seen, and I'm trying to use it to create a frequency list. I have tens of millions of sentences I want to analyze, but it took three days just to analyze 1 million. In comparison to something like mecab, mecab only took half an hour.

I am currently running the cli on each line, getting the JSON output, and working with that in NodeJS.

Let me know if there's anything I can do to speed up the process.

**Comment by wolfv506** [comment]
Hi,

I ran into the same issue as you. I don't know if it helps, but I found an adhoc solution with python. I managed to reduce the parse speed significantly by using a multithreadpool with concurrent futures and 8-10 threads (see attachement for benchmarks) . I also found that processing somewhat larger chunks of text at a time is more time efficient than passing single lines. As a rule of thumb I would read in the txt of a whole book/novel then split the text into evenly based chunks based on the amount of threads I used. 

Compared to mecab it's still significantly slower but I guess that's just the trade-off between accurracy and time effiency

![image](https://user-images.githubusercontent.com/68996908/141987208-84ce9609-f6b5-4207-bf09-bebd59dfea29.png)

**Comment by tshatrov** [comment]
Well, this segmenter was designed for interactive usage so it's not particularly efficient (I did optimize some things but only until it was 'good enough'. The main algorithm is quadratic wrt the length of the sentence, however that only applies to completely unsegmented text (with no punctuations or spaces or non-japanese characters at all). 

There's probably some overhead with calling cli on every sentence separately instead of bunching them together, separated by some sort of punctuation.

Also your approach seems to be single-threaded while Ichiran is thread-safe so the fastest approach would be native multithreading in Lisp, but launching cli in parallel should also work (although quite wasteful in terms of memory as each cli process is quite chunky).

**Comment by sethzh** [comment]
I should have mentioned that I already have the program spawning ichiran-cli concurrently with 8 workers.

I don't know much about concurrent or multi-threaded programming, so I'm not sure what the difference is.

Also, I tried processing larger chunks rather than single sentences, and the performance was a little slower than with single sentences.

You have to realize my program is held together by duct tape.

If I set this up on another machine I have of similar performance, and run them at the same time, it should take me half the time to get the results I need.

I have about 18,000,000 sentences I still want to cover, so that will take about 27 days with this method.

I also have to consider that since this is a frequency list, there are eventual diminishing returns. 10,000,000 instead of 1,000,000 will give me much more accurate frequency rankings, but 18,000,000 instead of 10,000,000 won't be nearly as useful. Limiting myself to 10,000,000 sentences would take about 2 weeks.

This is probably my best course of action other than upgrading my PC or figuring out how to do this in Lisp.

Thanks for the quick responses.

**Comment by Dillpickleschmidt** [comment]
# Ichiran Parallelization in Lisp: Processing Large Datasets Efficiently

I've successfully implemented ichiran parallelization in Lisp for processing large amounts of data. This solution achieves 100% utilization across all cores, significantly speeding up text processing tasks.

![CPU Utilization](https://github.com/user-attachments/assets/9dad5fb9-b2c5-416c-b245-9a79ae81d127)

Keep in mind I touched Lisp for the very first time yesterday so most of this is AI generated. I still had to spend 2 days debugging so this will likely still be useful for anyone wanting to use ichiran at larger scale.

## Input Format

This code assumes a CSV input format like this:

```
11,これさえあれば 俺は
11,本物の妖怪になれるんだ ヘヘッ
12,（桔梗(ききょう)）犬夜叉っ
13,おわっ
```

However, you can easily use Claude or Chat-GPT to modify the Lisp code to suit different input formats.

## Lisp Code

Here's the Lisp code that makes this possible:

```lisp
(ql:quickload '(:ichiran :lparallel :cl-csv :bordeaux-threads))

(defpackage :ichiran-file-processor
  (:use :cl :ichiran :lparallel)
  (:export :main))

(in-package :ichiran-file-processor)

(defparameter *chunk-size* 10000 "Number of lines to process in each chunk")
(defparameter *progress-interval* 100 "Number of lines between progress updates")

(setf lparallel:*kernel* (lparallel:make-kernel 8)) ; Use 8 cores

(defvar *line-counter* 0)
(defvar *total-lines* 0)
(defvar *line-counter-lock* (bt:make-lock))

(defun split-csv-line (line)
  "Split a CSV line into number and text parts"
  (let ((comma-pos (position #\, line)))
    (if comma-pos
        (cons (parse-integer (subseq line 0 comma-pos) :junk-allowed t)
              (string-trim '(#\Space #\Tab) (subseq line (1+ comma-pos))))
        (cons nil line))))

(defun process-sentence (sentence line-number)
  "Process a single Japanese sentence using Ichiran and format as CSV rows"
  (handler-case
    (mapcar (lambda (w)
              (list (write-to-string line-number)
                    (ichiran/dict:word-info-text w)
                    (ichiran/dict:word-info-kana w)))
            (ichiran/dict:simple-segment sentence))
    (error (e)
      (list (list (write-to-string line-number)
                  sentence
                  (format nil "ERROR: ~A" e))))))

(defun update-progress ()
  "Update and print progress if necessary"
  (bt:with-lock-held (*line-counter-lock*)
    (incf *line-counter*)
    (when (zerop (mod *line-counter* *progress-interval*))
      (let ((percentage (* 100 (/ *line-counter* *total-lines*))))
        (format t "Processed ~D/~D (~,3F%)~%" *line-counter* *total-lines* percentage)))))

(defun process-chunk (chunk)
  "Process a chunk of lines"
  (loop for (number . text) in chunk
        when number
          append (prog1 (process-sentence text number)
                   (update-progress))))

(defun read-input-file (filename)
  "Read the input file and return a list of (number . text) pairs"
  (with-open-file (in filename)
    (loop for line = (read-line in nil nil)
          while line
          collect (split-csv-line line))))

(defun count-lines (filename)
  "Count the total number of lines in the file"
  (with-open-file (in filename)
    (loop for line = (read-line in nil nil)
          while line count 1)))

(defun process-file-parallel (input-filename output-filename)
  "Process the input file in parallel and write results to the output CSV file"
  (let* ((input-data (read-input-file input-filename))
         (chunks (loop for i from 0 below (length input-data) by *chunk-size*
                       collect (subseq input-data i (min (+ i *chunk-size*) (length input-data)))))
         (results (pmap 'list #'process-chunk chunks)))
    (with-open-file (out output-filename
                         :direction :output
                         :if-exists :supersede
                         :if-does-not-exist :create)
      (cl-csv:write-csv-row '("Line Number" "Word" "Reading") :stream out)
      (dolist (chunk-result results)
        (dolist (row chunk-result)
          (cl-csv:write-csv-row row :stream out))))))

(defun main (filename)
  "Main function to process a file and write results to output.csv"
  (let* ((directory (directory-namestring filename))
         (output-filename (merge-pathnames "output.csv" directory)))
    (format t "Processing file: ~A~%" filename)
    (format t "Output will be written to: ~A~%~%" output-filename)
    (setf *line-counter* 0)
    (setf *total-lines* (count-lines filename))
    (format t "Total lines to process: ~D~%~%" *total-lines*)
    (time
     (handler-case
         (process-file-parallel filename output-filename)
       (error (e)
         (format t "An error occurred: ~A~%" e))))
    (format t "~%Processing complete. Total lines processed: ~D~%" *line-counter*)
    (format t "Results written to ~A~%" output-filename)))

;; Example usage:
;; (ichiran-file-processor:main "path/to/your/input.csv")
```

## Output

This code segments words into text and kana, separated by ";" where each word is placed on a new line. Again, you can modify this with Claude and Chat-GPT. Refer to the ichiran installation guide for common commands. Also, check out the package.lisp file in the ichiran directory to see all the functions it outputs. 

```
12,（,（
12,桔梗,ききょう
12,(,(
12,ききょう,(ききょう)
12,)）,)）
12,犬夜叉,いぬやしゃ
12,っ,っ
13,お,お
13,わ,わ
13,っ,っ
```

*Sometimes ichiran puts kana in parentheses. Sometimes there is more than 1 kana representation listed in parentheses, which are separated by Japanese space characters "　".

## Setup and Usage Instructions

1. Follow the ichiran installation instructions.
2. Create a new directory for this Lisp project (just one file) next to the ichiran folder in `quicklisp/local-projects`.
3. Create an `ichiran-file-processor.lisp` file and paste in the code above.
4. Run SBCL with increased dynamic space size:
   ```
   sbcl --dynamic-space-size 32768
   ```
   > Important: Adjust the size based on your available memory. This step is crucial to avoid random errors.

5. Navigate to the repository you created (folder containing `ichiran-file-processor.lisp`).
6. Load the file:
   ```lisp
   (load "ichiran-file-processor.lisp")
   ```
7. Run the main function:
   ```lisp
   (ichiran-file-processor:main "transcripts.csv")
   ```
   Replace "transcripts.csv" with your input file name.

## Notes
- This is my first Lisp project, created with the assistance of Claude 3.5 Sonnet. Expect some weirdness.
- If anyone is interested, I skimmed through [this](https://www.youtube.com/watch?v=LqBbGFMPcDI) video to get a basic idea of how to load packages and libraries like ichiran in lisp, and how to use quickload.
