### ISSUE TITLE
Clarification on seq number meaning

### ISSUE THREAD

**Issue by molesquirrel** [tshatrov/ichiran#21]
First off, thanks for your work on this project!

I'd like to know how the seq number is generated for words that have conjugations applied to them. For example, 得られ returns 
`[[[[["erare",{"reading":"\u5F97\u3089\u308C \u3010\u3048\u3089\u308C\u3011","text":"\u5F97\u3089\u308C","kana":"\u3048\u3089\u308C","score":240,"seq":11132474,"conj":[{"prop":[{"pos":"v1","type":"Continuative (~i)"}],"via":[{"prop":[{"pos":"v1","type":"Potential"},{"pos":"v1","type":"Passive"}],"reading":"\u5F97\u308B \u3010\u3048\u308B\u3011","gloss":[{"pos":"[v1,vt]","gloss":"to get; to earn; to acquire; to procure; to gain; to secure; to attain; to obtain; to win","info":"\u7372\u308B esp. refers to catching wild game, etc."},{"pos":"[v1,vt]","gloss":"to understand; to comprehend"},{"pos":"[v1,vt]","gloss":"to receive something undesirable (e.g. a punishment); to get (ill)"},{"pos":"[aux-v,v1,vt]","gloss":"to be able to ..., can ...","info":"after the -masu stem of a verb"}],"readok":true}],"readok":true}]},[]]],240]]]`

Specifically, a seq number of 1132474. 得る has an edict number of 1588760, so I'm wondering if there is a way to extract or reveal the edict number of the dictionary form of conjugated terms.

**Comment by tshatrov** [comment]
The conjugation numbers are assigned sequentially after the main dictionary is loaded.

There's a bunch of ways to get the source id. for example

```
ICHIRAN/DICT> (select-conjs 11132474)
(#<CONJUGATION 1588760 -> 10203029 -> 11132474>)
ICHIRAN/DICT> (seq-from (first (select-conjs 11132474)))
1588760
```

This means that it's a double conjugation from 1588760 (得る) to 10203029 (得られる) and then to 11132474 (得られ). `seq-from` of conjugation object is always a dictionary form.

**Comment by molesquirrel** [comment]
Thanks! Given that the conjugation data is already partially in the json results, if you ever get a chance to add those numbers in there, I imagine it'd be quite useful to anyone who is bridging ichiran to a pre-existing system that relies on jmdict.

**Comment by molesquirrel** [comment]
Apologies for reopening this - a follow-up question: is it possible to use the ichiran-cli with the -e argument to call this from the cli (so that it can be called and result stored from another language making calls to the cli?)

**Comment by tshatrov** [comment]
Hi, I'm not sure what *this* is in "to call this from the cli" but -e can execute arbitrary lisp code so it should be possible.

I'm also not sure what you mean by exporting conjugation table, the conjugation rules are available [from JMdict repository](https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data). Specifically conjo.csv.

**Comment by molesquirrel** [comment]
Thanks for the reply. Those two tables are indeed quite helpful, I appreciate it.

**Comment by fasiha** [comment]
> `ICHIRAN/DICT> (select-conjs 11132474)`

Super-noob question here 😅 can I run this from Docker?

`docker exec ichiran-main-1 ichiran-cli -e "(ichiran/dict::select-conjs 11132474)"` doesn't work (`No database connection selected.`) and starting SBCL with `docker exec -it ichiran-main-1 ichiran-sbcl` and then running `(select-conjs 11132474)` doesn't work because of `UNDEFINED-FUNCTION`.

**Comment by tshatrov** [comment]
For most `ichiran/dict` functions to work there must be an established connection to the database. This can be done with using `(with-db nil ...)` wrapper (which would use the default `*connection*` in settings.lisp). With specified package it would be `ichiran/conn:with-db`. The following worked for me:

```
PS C:\lisp\ichiran> .\ichiran-cli -e "(ichiran/conn:with-db nil (ichiran/dict::select-conjs 11132474))"

(#<ICHIRAN/DICT::CONJUGATION 1569530 -> 10132248 -> 11132474>)
```

>running (select-conjs 11132474) doesn't work because of UNDEFINED-FUNCTION.

Could be explained by being in the wrong package. You could execute `(in-package :ichiran/dict)` followed by running
`(with-db nil (select-conjs 11132474))`

**Comment by fasiha** [comment]
Perfect, thank you, that works perfectly!

```
$ docker exec ichiran-main-1 ichiran-cli -e "(ichiran/conn:with-db nil (ichiran/dict::select-conjs 11132474))"

(#<ICHIRAN/DICT::CONJUGATION 1569530 -> 10132248 -> 11132474>)
1
```
and similarly if you want to get this from Postgres (a bit faster),
```
docker exec -it ichiran-pg-1 psql -U postgres -h 127.0.0.1 jmdict0122 --csv -t -c "select \"from\" from conjugation where seq=11132474"
1569530
```
(The `-t` tells `psql` to not print a header, just the row data.) Of course here you lose the intermediate conjugation that `select-conjs` gives you.

I agree it might be nice if this was bundled with the JSON output of `ichiran-cli -f` but the above is totally doable. Again, many thanks!

**Comment by tshatrov** [comment]
The intermediate conjugation is available from `via` column (`select \"from\", via from conjugation`)

**Comment by nienkeboomsma** [comment]
> Given that the conjugation data is already partially in the json results, if you ever get a chance to add those numbers in there, I imagine it'd be quite useful to anyone who is bridging ichiran to a pre-existing system that relies on jmdict.

Like frequency lists with cross-references to a user's known words. It would be extremely useful if the conjugated entries had the seq-from included.
