### ISSUE TITLE
Support for がい/かい suffix

### ISSUE THREAD

**Issue by dddlr** [tshatrov/ichiran#24]
Hiya,

I noticed that there doesn't seem to be support for the [verb masu stem] + がい +  structure, and ichi.moe instead would try to parse this as everything except 甲斐 😅

Here's an example from the 転生したら剣でした manga chapter 58. This chapter is available on sites like klmanga[.]com if more context is needed.

> ...だが
> それでこそ
> 狩りがいのある獣よ！

It would be really awesome if ichi.moe could parse this structure somehow. One quick fix I thought of was to treat the whole がいのある as a variant of 甲斐がある so that JMDict's entry for 甲斐がある appears. But then again, I realize that [several other structures involving かい/がい also exist](https://nihongokyoshi-net.com/2019/04/23/jlptn2-grammar-kaigaatte/) and aren't parsed properly by ichi.moe, so there's likely far more robust approaches than my suggestion here.

Thank you :)

**Comment by tshatrov** [comment]
Thanks for reporting, I'll see when I can get around to fixing this.
