### ISSUE TITLE
JSON returned by ichiran/cli

### ISSUE THREAD

**Issue by blunderedbishop** [tshatrov/ichiran#25]
I'm using ichiran-cli with the `-f` argument to provide my scripts with the full segmentation of a sentence. I'm writing my own little parser for the returned JSON, but I'm having problems since there's lots of structure in it, and I don't know where to find everything or what exactly should I expect from it. Here is an example:

`['itsuni', {'reading': '一に 【いつに】', 'text': '一に', 'kana': 'いつに', 'score': 128, 'seq': 1160930, 'gloss': [{'pos': '[adv]', 'gloss': 'solely; entirely; only; or'}], 'conj': []}, []]`

Sometimes the 'gloss' list is empty, sometimes the 'conj' list is, and sometimes both in the case of e.g. suffixes. I don't know where to find the tense in the case of verbs.
Where can I find an explanation of the structure of the JSON that is returned by ichiran-cli?

**Comment by blunderedbishop** [comment]
Thank you very much. That should cover most words one encounters regularly. Is there no reference where I can find every type of word and structure that could be returned? If there is none, consider the issue solved.

**Comment by tshatrov** [comment]
@blunderedbishop you're probably missing conj.csv file from [here](https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data) or *jmdict-data* variable is pointing to the incorrect path in settings.lisp
