### ISSUE TITLE
Spliting words functionality

### ISSUE THREAD

**Issue by dndeus** [tshatrov/ichiran#41]
Hello and thank you for your work!!

Is it possible somehow to use only the word splitting functionality of this package?

**Comment by tshatrov** [comment]
What do you mean by that? You can use just the word splitting functionality, there's not much other functionality anyway.

**Comment by tshatrov** [comment]
```
ICHIRAN/DICT> (mapcar 'word-info-kana (simple-segment "りんごを食べる"))
("りんご" "を" "たべる")
```

**Comment by dndeus** [comment]
I'm sorry but I'm not familiar with lisp to be honest.

The way I use it and to export the json format, is according to documentation

docker exec -it ichiran-main-1 ichiran-cli -f "りんごを食べる"

How to use your code snippet from above?

Thanks!

**Comment by tshatrov** [comment]
You can use the -e argument of ichiran-cli to execute arbitrary Lisp code (you might have to escape the quote characters though to pass it as an argument)

```
>ichiran-cli -e "(join \" \" (mapcar 'word-info-kana (simple-segment \"りんごを食べます\")))"

Output:
 "りんご を たべます"
```

**Comment by dndeus** [comment]
Oh I see, that way I can whatever function you have on your code.

Great, works nicely!

Thanks for the help!!
