### ISSUE TITLE
Segmentation issue

### ISSUE THREAD

**Issue by KuhaKenuvo** [tshatrov/ichiran#48]
"ものにも" will be separated into "も", "のに", "も".
But the right separation would be "もの", "にも".

**Comment by tshatrov** [comment]
Confirmed. [Example sentences](https://ejje.weblio.jp/sentence/content/%22%E3%82%82%E3%81%AE%E3%81%AB%E3%82%82%22) for reference.

**Comment by tshatrov** [comment]
fixed
