### ISSUE TITLE
Docker setup with 2024 January dump complains

### ISSUE THREAD

**Issue by fasiha** [tshatrov/ichiran#49]
Hello hello! Congratulations on the big 2024 release 😁 I'm trying to modify the Docker setup for this release but I'm running into this Postgres error on the `docker compose up` step and wondering if this is an issue with the release or if it's Docker-related:
```
ERROR:  relation "sense_prop" does not exist at character 16
STATEMENT:  (SELECT * FROM sense_prop WHERE ((seq = 2089020) and (tag = E'pos') and (text = E'cop-da')))
```
I had to change a couple of small things to the Docker setup (see my diff at https://github.com/tshatrov/ichiran/compare/master...fasiha:ichiran:2024-jan-release?expand=1). Thanks for any tips! Thanks for continuing to support this great project 🫶

**Comment by tshatrov** [comment]
Yeah, I don't really use the docker stuff, it was contributed by another user. Is there a way to inspect the database, it's more likely that it's empty than that table being the only one missing. There could've been an error while restoring the database which I expect would be ignored.
