### ISSUE TITLE
jmdict.csv does not exist

### ISSUE THREAD

**Issue by Dillpickleschmidt** [tshatrov/ichiran#52]
## Issue Summary

When running the unit tests for the Ichiran project, all tests pass but I get an execution error due to a missing file. This issue seems to appear only when working with JSON.

### Test Results

Unit Test Summary
| 750 assertions total
| 750 passed
| 0 failed
| 1 execution errors
| 0 missing tests

| Execution error:
| The file #P"C:/Users/drkuz/quicklisp/local-projects/ichiran/data/jmdict.csv"
does not exist:
The system cannot find the file specified.
|
JSON-CONSISTENCY-TEST: 1 assertions passed, 0 failed, and an execution error.

#<TEST-RESULTS-DB Total(750) Passed(750) Failed(0) Errors(1)>

### Issue Description

The test suite runs 750 assertions, all of which pass but I get an execution error. The execution error is because the file `jmdict.csv` is missing from the specified directory. 

### File Locations

- **Local Directory**: `C:/Users/drkuz/quicklisp/local-projects/ichiran/data/`
- **Missing File**: `jmdict.csv`

### Configuration

Here’s my `settings.lisp` file:

```lisp
(in-package #:ichiran/conn)

(defparameter *connection* '("ichiran" "postgres" "myPassword" "localhost"))

(defparameter *connections* '((:old "jmdict_old" "postgres" "password" "localhost")
                              (:test "jmdict_test" "postgres" "password" "localhost")))

(in-package #:ichiran/dict)

(defparameter *jmdict-path* #p"/home/you/dump/JMdict_e")

(defparameter *jmdict-data* #p"C:/Users/drkuz/quicklisp/local-projects/ichiran/data/jmdict")

(in-package #:ichiran/kanji)

(defparameter *kanjidic-path* #P"/home/you/dump/kanjidic2.xml")
```

- `C:/Users/drkuz/quicklisp/local-projects/ichiran/data/jmdict` is where I placed [these files](https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data).

I’m not sure where to get the missing jmdict.csv file. I'm trying to parse some lines of text in bulk, but it also randomly throws this error instead of parsing the line, leading to skipping issues. Can anyone help with providing the correct file or suggest how to resolve this issue?

**Comment by tshatrov** [comment]
Try to ensure *jmdict-data* ends with / otherwise it's not parsed as a directory.

**Comment by Dillpickleschmidt** [comment]
> Try to ensure `*jmdict-data*` ends with / otherwise it's not parsed as a directory.

Wohoo! Thanks :D
