### ISSUE TITLE
"六代目", "三つ目" and other words using 目 throws error

### ISSUE THREAD

**Issue by theUnrealSamurai** [tshatrov/ichiran#55]
<img width="641" alt="image" src="https://github.com/user-attachments/assets/2d8f6c07-78a6-4034-9d8e-142b8dcff94c">

But it works perfectly fine in the website ichi.moe. Is there anyway I could get the same working locally?

**Comment by tshatrov** [comment]
Do you have a full traceback? It works on my local machine but it's possible that docker version doesn't initialize correctly.

**Comment by theUnrealSamurai** [comment]
The last screenshot was from ichiran-cli. I'm sorry I didn't realize there was more error log. ichiran-cli didn't output anything else other than that. 

This one is from the SBCL interpreter in linux. 
![image](https://github.com/user-attachments/assets/20c2e90f-6672-4820-a7b5-7ac53cc40493)

This one is from the docker
![image](https://github.com/user-attachments/assets/68d05c37-8eaa-4f91-9fcc-1adbac817979)


I'm not sure if this one is related but all the tests does not pass on linux. To pass all the tests I have to set this line in settings.lisp to 
`(defparameter *jmdict-data* #p"/home/samurai/quicklisp/local-projects/ichiran/jmdictdb/jmdictdb/")` and run tests once in the SBCL interpreter. Then I have to change it to `(defparameter *jmdict-data* #p"/home/samurai/quicklisp/local-projects/ichiran/jmdictdb/jmdictdb/data")` and rerun the test without exiting from SBCL to pass all the tests. 

I have to do this every time I re open SBCL interpreter. But all the tests pass in docker without any errors. 

when the path is set to `/jmdictdb` it looks for a data.csv file which is not found in the entire jmdict repo
 
![image](https://github.com/user-attachments/assets/ce5d33fb-8ea8-4547-ad79-3b118ba7ca76)

Hey Thanks for the help and quick response!

**Comment by theUnrealSamurai** [comment]
Is there any update on it? I would appreciate it if you could tell me what to fix or where to look, I'll try debug, I'll see what I can do.

**Comment by tshatrov** [comment]
The path to *jmdict-data* must end with / and has to contain files from [this repository](https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data) as stated in the README.

The issue from the first screenshot looks like maybe the terminal not parsing the japanese characters correctly. The second one I have never seen and cannot reproduce.

**Comment by tshatrov** [comment]
Just pushed a fix, https://github.com/tshatrov/ichiran/commit/621196829e2c29577a8168e08efd9a78414513d9 I think this should resolve the problem with the counters in ichiran-cli.

**Comment by theUnrealSamurai** [comment]
Solved both the problems. 
Changed the path to end with / All the tests passes now.
And the counters work fine with the new update. 
Thank you!
