### ISSUE TITLE
If only they used ichi.moe's engine...

### ISSUE THREAD

**Issue by hobodrifterdavid** [tshatrov/ichiran#7]
https://news.ycombinator.com/item?id=22033309

:-) Hello. Yes, the romaji support sucks. Can you help me a little? I'm tokenising with Mecab through a python lib, then the furigana of tokens is converted on the front-end with wanakana.js. You can mail me on hobodrifterdavid@gmail.com , maybe I can call you? David

**Comment by tshatrov** [comment]
Closing as it's not an issue with the codebase.
You can ask questions about the implementation via `admin (at) ichi.moe`.
