### ISSUE TITLE
何だと does not get split correctly before verbs that take the と particle

### ISSUE THREAD

**Issue by max-kamps** [tshatrov/ichiran#9]
Hello, is this the right place to report segmentation issues? If so, here's one:
I can mostly find this expression used before 思う (i.e. 何だと思う), but I *think* in principle it should also apply to other verbs that take と.

Example sentences:
- http://tatoeba.org/eng/sentences/show/189060 [Shortened for clarity]
  > 最良の方法は何だと思いますか。 - What do you think is the best way?
  
  Expected segmentation: `最良　の　方法　は　何　だ　と　思います　か`
  Ichiran segmentation: `最良　の　方法　は　何だと　思います　か`
- http://tatoeba.org/eng/sentences/show/81700
  > 僕を何だと思っているのか。 - What do you take me for? / "What do you think I am."
  
    Expected segmentation: `僕　を　何　だ　と　思っている　のか`
    Ichiran segmentation: `僕　を　何だと　思っている　のか`

**Comment by tshatrov** [comment]
I guess it can be split up in these cases...

**Comment by tshatrov** [comment]
Fixed.
